name: Generate Installable Plugin and Upload zip as Release Asset
on:
  release:
    types: [published]

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Node Setup
        uses: actions/setup-node@v2
      - name: Build Project
        run: |
          composer install --no-dev --optimize-autoloader
          npm install
          npm run build
          npm run pluginSidebar:build
          rm -rf node_modules
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            membergate.php
            utils.php
            templates/*
            src/*
            extend-block-editor/*
            assets/*
            vendor/*

